version: '3'

services:
    web:
        build: ./docker.dev
        networks:
          - web
        ports:
          - '1313:1313'
          - '5000:5000'
        volumes:
          - .:/usr/src/app
        stdin_open: true
        tty: true
        command: bash -c "nginx && bash"
networks:
    web:
        driver: bridge