version: '3'

services:
    hugo:
        build: ./docker.dev
        ports:
          - '1313:1313'
          - '5000:5000'
        volumes:
          - .:/usr/src/app
        stdin_open: true
        tty: true
        command: bash -c "nginx && bash"